package com.example.accessibilityv1

enum class KeyAction {
    EMPTY,
    BUTTON_A_PRESSED,
    BUTTON_B_PRESSED,
    BUTTON_UP_PRESSED,
    BUTTON_DOWN_PRESSED,
    BUTTON_LEFT_PRESSED,
    BUTTON_RIGHT_PRESSED,
    BUTTON_HOME_PRESSED,
    BUTTON_A_RELEASED,
    BUTTON_B_RELEASED,
    BUTTON_UP_RELEASED,
    BUTTON_DOWN_RELEASED,
    BUTTON_LEFT_RELEASED,
    BUTTON_RIGHT_RELEASED,
    BUTTON_HOME_RELEASED
}